"""P1S4: orders, fills, positions, risk_limits, risk_checks

Revision ID: 045280f6aa2d
Revises: 67233e8aac68
Create Date: 2026-05-21 13:33:59.219374

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '045280f6aa2d'
down_revision: str | Sequence[str] | None = '67233e8aac68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside', native_enum=False, length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype', native_enum=False, length=16), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('tif', sa.Enum('DAY', 'GTC', 'IOC', 'FOK', name='timeinforce', native_enum=False, length=8), nullable=False),
    sa.Column('extended_hours', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_RISK', 'PENDING_SUBMIT', 'SUBMITTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCELED', 'EXPIRED', 'REJECTED', 'REPLACED', name='orderstatus', native_enum=False, length=24), nullable=False),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.Enum('MANUAL', 'STRATEGY', 'AGENT_STRATEGY', 'AGENT_PROPOSAL', 'PINE', name='ordersourcetype', native_enum=False, length=24), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('parent_order_id', sa.Integer(), nullable=True),
    sa.Column('risk_check_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_orders_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_order_id'], ['orders.id'], name=op.f('fk_orders_parent_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_check_id'], ['risk_checks.id'], name=op.f('fk_orders_risk_check_id_risk_checks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_orders_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('broker_order_id', name=op.f('uq_orders_broker_order_id'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_symbol_created', ['symbol_id', 'created_at'], unique=False)
        batch_op.create_index('ix_orders_user_status_created', ['user_id', 'status', 'created_at'], unique=False)

    op.create_table('risk_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('agent_session_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Enum('PASS', 'REJECT', name='riskdecision', native_enum=False, length=16), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_risk_checks_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_checks'))
    )
    with op.batch_alter_table('risk_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_checks_order_id'), ['order_id'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('broker_fill_id', sa.String(length=64), nullable=True),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_fills_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fills'))
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_filled_at'), ['filled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_order_id'), ['order_id'], unique=False)

    op.create_table('risk_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.Enum('GLOBAL', 'ACCOUNT', 'STRATEGY', 'AGENT_SESSION', name='riskscopetype', native_enum=False, length=32), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('max_position_qty', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_position_notional', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('max_gross_exposure', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('max_daily_loss', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('max_orders_per_minute', sa.Integer(), nullable=True),
    sa.Column('allow_short', sa.Boolean(), nullable=False),
    sa.Column('allowed_symbols', sa.JSON(), nullable=True),
    sa.Column('denied_symbols', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_limits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_limits'))
    )
    with op.batch_alter_table('risk_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_limits_user_id'), ['user_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unrealized_pl', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unrealized_plpc', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_positions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_positions_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_positions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('account_id', 'symbol_id', name='uq_positions_account_symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    with op.batch_alter_table('risk_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_limits_user_id'))

    op.drop_table('risk_limits')
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_order_id'))
        batch_op.drop_index(batch_op.f('ix_fills_filled_at'))

    op.drop_table('fills')
    with op.batch_alter_table('risk_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_checks_order_id'))

    op.drop_table('risk_checks')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_user_status_created')
        batch_op.drop_index('ix_orders_symbol_created')

    op.drop_table('orders')
    # ### end Alembic commands ###
