"""P3: agent_sessions, agent_messages, agent_tool_invocations

Revision ID: 0e039e08250e
Revises: bdd6fe959f89
Create Date: 2026-05-28 18:15:30.901484

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0e039e08250e'
down_revision: str | Sequence[str] | None = 'bdd6fe959f89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('B1_READONLY', 'B2_INTERACTIVE', 'B3_AUTONOMOUS', name='agentsessionmode', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'CAPPED', 'ERROR', name='agentsessionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('daily_budget_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sessions'))
    )
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL_USE', 'TOOL_RESULT', 'SYSTEM', name='agentmessagerole', native_enum=False, length=24), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_message_id'], ['agent_messages.id'], name=op.f('fk_agent_messages_parent_message_id_agent_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], name=op.f('fk_agent_messages_session_id_agent_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_agent_messages_session_ts', ['session_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_ts'), ['ts'], unique=False)

    op.create_table('agent_tool_invocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_text', sa.String(length=2048), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], name=op.f('fk_agent_tool_invocations_message_id_agent_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], name=op.f('fk_agent_tool_invocations_session_id_agent_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tool_invocations'))
    )
    with op.batch_alter_table('agent_tool_invocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tool_invocations_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_agent_tool_invocations_session_ts', ['session_id', 'ts'], unique=False)
        batch_op.create_index('ix_agent_tool_invocations_tool_ts', ['tool_name', 'ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_tool_invocations', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_tool_invocations_tool_ts')
        batch_op.drop_index('ix_agent_tool_invocations_session_ts')
        batch_op.drop_index(batch_op.f('ix_agent_tool_invocations_session_id'))

    op.drop_table('agent_tool_invocations')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_ts'))
        batch_op.drop_index('ix_agent_messages_session_ts')
        batch_op.drop_index(batch_op.f('ix_agent_messages_session_id'))

    op.drop_table('agent_messages')
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_user_id'))

    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
