"""P1S2: accounts_state cache table

Revision ID: 67233e8aac68
Revises: 656c0c6d51b1
Create Date: 2026-05-21 10:24:14.850859

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67233e8aac68'
down_revision: str | Sequence[str] | None = '656c0c6d51b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('last_equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('daytrade_count', sa.Integer(), nullable=False),
    sa.Column('day_change', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('day_change_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pattern_day_trader', sa.Boolean(), nullable=False),
    sa.Column('trading_blocked', sa.Boolean(), nullable=False),
    sa.Column('account_blocked', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_accounts_state_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts_state')),
    sa.UniqueConstraint('account_id', name=op.f('uq_accounts_state_account_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts_state')
    # ### end Alembic commands ###
