"""P4 strategies has_pending_reload + pending_reload_at

Revision ID: bdd6fe959f89
Revises: dd3f2a924c0c
Create Date: 2026-05-26 19:55:24.305042

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bdd6fe959f89'
down_revision: str | Sequence[str] | None = 'dd3f2a924c0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_pending_reload', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('pending_reload_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_column('pending_reload_at')
        batch_op.drop_column('has_pending_reload')

    # ### end Alembic commands ###
