"""P4 §2: backtest_jobs table

Revision ID: dd3f2a924c0c
Revises: f39243ab699f
Create Date: 2026-05-25 12:38:18.652225

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd3f2a924c0c'
down_revision: str | Sequence[str] | None = 'f39243ab699f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='backtestjobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('current_ts', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_text', sa.String(length=2048), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['backtest_results.id'], name=op.f('fk_backtest_jobs_result_id_backtest_results'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_backtest_jobs_strategy_id_strategies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_backtest_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_jobs'))
    )
    with op.batch_alter_table('backtest_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_jobs_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index('ix_backtest_jobs_strategy_status', ['strategy_id', 'status'], unique=False)
        batch_op.create_index('ix_backtest_jobs_submitted_at', ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_jobs_user_id'))
        batch_op.drop_index('ix_backtest_jobs_submitted_at')
        batch_op.drop_index('ix_backtest_jobs_strategy_status')
        batch_op.drop_index(batch_op.f('ix_backtest_jobs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_jobs_status'))

    op.drop_table('backtest_jobs')
    # ### end Alembic commands ###
