"""P2S2 strategies, strategy_runs, signals, backtest_results

Revision ID: e8cb970af19b
Revises: 045280f6aa2d
Create Date: 2026-05-22 17:55:04.478226

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8cb970af19b'
down_revision: str | Sequence[str] | None = '045280f6aa2d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('PYTHON', 'PINE', 'AGENT', name='strategytype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'BACKTEST', 'PAPER', 'LIVE', 'HALTED', 'ERROR', name='strategystatus', native_enum=False, length=16), nullable=False),
    sa.Column('code_path', sa.String(length=512), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('symbols_json', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=False),
    sa.Column('risk_limits_id', sa.Integer(), nullable=True),
    sa.Column('error_text', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_limits_id'], ['risk_limits.id'], name=op.f('fk_strategies_risk_limits_id_risk_limits'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)

    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('equity_curve_json', sa.JSON(), nullable=False),
    sa.Column('trades_json', sa.JSON(), nullable=False),
    sa.Column('range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_backtest_results_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_results'))
    )
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_results_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ENTRY', 'EXIT', 'FLAT', 'INFO', 'AGENT_ACTION', 'PINE_ALERT', name='signaltype', native_enum=False, length=24), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_signals_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_signals_symbol_id_symbols'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_strategy_received', ['strategy_id', 'received_at'], unique=False)
        batch_op.create_index('ix_signals_symbol_received', ['symbol_id', 'received_at'], unique=False)

    op.create_table('strategy_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'BACKTEST', 'PAPER', 'LIVE', 'HALTED', 'ERROR', name='strategystatus', native_enum=False, length=16), nullable=False),
    sa.Column('error_text', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_runs_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_runs'))
    )
    with op.batch_alter_table('strategy_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_runs_strategy_id'), ['strategy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_runs_strategy_id'))

    op.drop_table('strategy_runs')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index('ix_signals_symbol_received')
        batch_op.drop_index('ix_signals_strategy_received')

    op.drop_table('signals')
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_results_strategy_id'))

    op.drop_table('backtest_results')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_user_id'))

    op.drop_table('strategies')
    # ### end Alembic commands ###
