"""P4: pine_webhook_secret on users

Revision ID: f39243ab699f
Revises: e8cb970af19b
Create Date: 2026-05-23 21:14:51.515937

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f39243ab699f'
down_revision: str | Sequence[str] | None = 'e8cb970af19b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pine_webhook_secret', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_pine_webhook_secret'), ['pine_webhook_secret'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_pine_webhook_secret'))
        batch_op.drop_column('pine_webhook_secret')

    # ### end Alembic commands ###
