"""Registry genesis id format (Round 5 owner ruling): a canonical lowercase UUIDv4 string.

A genesis id is generated by ``uuid.uuid4()`` (CSPRNG-backed) inside ``RunRegistry.enroll_new``.
It is an IDENTITY MARKER for a research lineage, NOT authentication: anyone who can read a
registry file can read its genesis id, and a copied registry keeps it (Level 2 limitation).
"""

from __future__ import annotations

import re
import uuid

_UUID4_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")


def is_canonical_uuid4(value: object) -> bool:
    """True only for the canonical lowercase hyphenated text form of a version-4 RFC 4122 UUID."""
    return isinstance(value, str) and _UUID4_RE.fullmatch(value) is not None


def new_genesis_id() -> str:
    """A fresh genesis id (``uuid.uuid4()``; os.urandom-backed)."""
    return str(uuid.uuid4())


PURE_FUNCTIONS = ("is_canonical_uuid4", "new_genesis_id")
