#!/usr/bin/env bash
# TradingWorkbench — EC2 user-data bootstrap (Ubuntu 24.04 arm64, t4g.medium).
#
# Brings up the PAPER stack on a fresh instance per ADR 0032. Idempotent enough
# to re-run. Runs as root via cloud-init. Phase 1 boots with a SCRATCH DB and the
# scheduler DISARMED — it touches no live books. The real DB is restored only at
# cutover (see Docs/runbook/aws-migration.md).
#
# Prereqs handled OUTSIDE this script (see runbook):
#   - Instance role with ssm:GetParameter* on /workbench/prod/* and s3:PutObject on the backup bucket
#   - SSM SecureString params populated under /workbench/prod/*
#   - Security group: inbound SSH (22) from your IP only; no app ports
#
# Edit the CONFIG block, then paste as the instance's User data (or pass via --user-data).
set -euo pipefail

####################  CONFIG (env-overridable; CloudFormation passes these)  ####################
REPO_URL="${REPO_URL:-https://github.com/jayw04/AI-TRADING-APP.git}"
REPO_BRANCH="${REPO_BRANCH:-main}"
APP_DIR="${APP_DIR:-/opt/workbench}"
REPO_DIR="${APP_DIR}/app"
AWS_REGION="${AWS_REGION:-us-east-1}"
SSM_PREFIX="${SSM_PREFIX:-/workbench/prod}"
TZ_NAME="${TZ_NAME:-America/New_York}"
SWAP_GB="${SWAP_GB:-4}"
# Phase 1 = scratch/disarmed. Flip to "true" ONLY at cutover, with the laptop stopped.
SCHEDULER_ENABLED="${SCHEDULER_ENABLED:-false}"
LIVE_TRADING_ALLOWED="${LIVE_TRADING_ALLOWED:-false}"   # never true on this box (paper-only, ADR 0032)
HOST_ID="${WORKBENCH_HOST_ID:-ec2-paper}"               # heartbeat host id (ADR 0032)
################################################################################################

log() { echo "[bootstrap $(date -u +%FT%TZ)] $*"; }

# --- 0. Base packages ------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y ca-certificates curl gnupg git unzip jq awscli

# --- 1. Timezone (ADR 0032: ET, scheduler correctness) ---------------------
timedatectl set-timezone "${TZ_NAME}"
log "timezone set to $(cat /etc/timezone)"

# --- 2. Swap (rebalance-spike cushion) -------------------------------------
if [ ! -f /swapfile ]; then
  fallocate -l "${SWAP_GB}G" /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=$((SWAP_GB*1024))
  chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
  log "swap enabled (${SWAP_GB}G)"
fi

# --- 3. Docker + compose plugin (arm64) ------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
systemctl enable --now docker   # restart-on-boot (ADR 0032)
log "docker $(docker --version)"

# --- 4. Fetch secrets from SSM into a root-only .env -----------------------
# Pulls each SecureString and writes /opt/workbench/.env (chmod 600).
mkdir -p "${APP_DIR}/data"
ENV_FILE="${APP_DIR}/.env"
get_ssm() { aws ssm get-parameter --region "${AWS_REGION}" --name "$1" --with-decryption \
              --query Parameter.Value --output text 2>/dev/null || true; }

{
  echo "# generated by ec2-user-data.sh — DO NOT COMMIT"
  echo "WORKBENCH_ENV=paper-cloud"
  echo "TZ=${TZ_NAME}"
  echo "WORKBENCH_HOST=0.0.0.0"
  echo "WORKBENCH_DB_URL=sqlite+aiosqlite:////app/data/workbench.sqlite"
  echo "WORKBENCH_SCHEDULER_ENABLED=${SCHEDULER_ENABLED}"
  echo "WORKBENCH_LIVE_TRADING_ALLOWED=${LIVE_TRADING_ALLOWED}"
  echo "WORKBENCH_HOST_ID=${HOST_ID}"
  echo "WORKBENCH_MASTER_KEY=$(get_ssm ${SSM_PREFIX}/WORKBENCH_MASTER_KEY)"
  echo "ANTHROPIC_API_KEY=$(get_ssm ${SSM_PREFIX}/ANTHROPIC_API_KEY)"
  echo "WORKBENCH_MCP_KEY=$(get_ssm ${SSM_PREFIX}/WORKBENCH_MCP_KEY)"
  echo "AGENT_API_KEY=$(get_ssm ${SSM_PREFIX}/AGENT_API_KEY)"
  echo "MCP_BACKEND_TOKEN=$(get_ssm ${SSM_PREFIX}/MCP_BACKEND_TOKEN)"
  # Paper-only: NO ALPACA_LIVE_* here, ever (ADR 0032). Paper creds live encrypted
  # in the migrated DB; left blank in env on purpose.
  echo "AGENT_DAILY_BUDGET_USD=2.0"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

# Fail fast if the master key (DB-paired) didn't resolve.
if ! grep -q '^WORKBENCH_MASTER_KEY=.\+' "${ENV_FILE}"; then
  log "FATAL: WORKBENCH_MASTER_KEY missing from SSM — backend would refuse to boot. Aborting."
  exit 1
fi
# Hard guard: refuse to proceed if any live secret leaked into the env.
if grep -Eq '^ALPACA_LIVE_' "${ENV_FILE}"; then
  log "FATAL: live Alpaca creds present on a paper-only box (ADR 0032). Aborting."
  exit 1
fi
log "secrets written to ${ENV_FILE}"

# --- 5. Clone repo + bring up the stack ------------------------------------
if [ ! -d "${REPO_DIR}/.git" ]; then
  git clone --branch "${REPO_BRANCH}" "${REPO_URL}" "${REPO_DIR}"
else
  git -C "${REPO_DIR}" fetch --all && git -C "${REPO_DIR}" checkout "${REPO_BRANCH}" && git -C "${REPO_DIR}" pull
fi

# Link the root-only env + data volume into the repo's expected locations.
ln -sf "${ENV_FILE}" "${REPO_DIR}/.env"
mkdir -p "${REPO_DIR}/data"
# Phase 1: scratch DB. (At cutover the runbook drops the real workbench.sqlite here.)
ln -sfn "${APP_DIR}/data" "${REPO_DIR}/data" 2>/dev/null || true

# Record the dispatching code version into the heartbeat (ADR 0032 R-heartbeat).
echo "WORKBENCH_CODE_VERSION=$(git -C "${REPO_DIR}" rev-parse --short HEAD 2>/dev/null || echo unknown)" >> "${ENV_FILE}"

cd "${REPO_DIR}"
# Native arm64 build. Use the prod overlay when present (TZ + flags + no source mounts).
COMPOSE_FILES="-f docker-compose.yml"
[ -f docker-compose.prod.yml ] && COMPOSE_FILES="${COMPOSE_FILES} -f docker-compose.prod.yml"
docker compose ${COMPOSE_FILES} build
docker compose ${COMPOSE_FILES} up -d

log "stack up. SCHEDULER_ENABLED=${SCHEDULER_ENABLED} (Phase 1 should be false)."
log "Reach the UI via SSH tunnel:  ssh -N -L 5173:127.0.0.1:5173 -L 8000:127.0.0.1:8000 ubuntu@<instance-ip>"
log "bootstrap complete."
