"""Strategy 9 v1.3/C40 transition planner v3.

Derived from v13_transition_planner.py (sha ece3f6e3...), which remains sealed and
unedited, by a single anchored replacement asserted unique: the embedded frozen
PLANNER v8 (Protocol v2.1, hardened). v8 = v7 bound to limits v8, which adds the
failure-taxonomy governance rule, the residual-debt lifecycle and the activation
invariants. No construction, sizing or economic figure changes.

PLANNER v7 (Transition Protocol v2.1). v7 = v6 bound to limits v7, which scopes
concentration-triggered completeness to joint-construction stages (B_cross_asset alone).
No construction, sizing or economic figure changes; the resolved policy block a manifest
carries now records joint_construction and concentration_completeness_applies per stage.

PLANNER v6 (Transition Protocol v2, owner rulings 2026-08-21). v6 = v5 with two
additions to the hashed manifest body and NO change to construction, sizing, gating or
any economic figure:

  * continuation_policy_resolved - the per-stage stage-continuation rule, resolved from
    the sealed limits v6 so that the owner approves the RULE together with the ORDERS it
    governs. Executor v8 re-derives it and refuses a manifest that discloses a different
    rule from the one it will apply.
  * residual_operational_debt - outstanding RESIDUAL_CLEANUP_REQUIRED obligations, plus
    an explicit conflict list naming any residual symbol this manifest also targets.

The limits path moves to _v7.json. Neither v6 nor v7 changes a numeric order-level gate;
that is asserted by the limits builder and re-asserted by the executor at load.

limits path moves from v13_frozen_execution_limits_v2.json to _v3.json. Limits are
embedded opaquely (sha256 + verbatim content) and no limits content key is read by
this planner, so the version move is confined to which file is embedded.

Authorized by the owner ruling of 2026-08-08. A manifest generated by this planner
is loadable by v13_transition_executor_v3.py; manifests from the v2 planner are
refused by v3, which is the intended fail-closed behaviour.

ORIGINAL DOCSTRING FOLLOWS
ONE_TIME_OPERATOR_EXECUTED_STRATEGY_REBALANCE — account 7 / strategy 9.

Governing classification (owner ruling 2026-07-27):
    execution_type:         ONE_TIME_OPERATOR_EXECUTED_STRATEGY_REBALANCE
    strategy_id:            9
    prior_interrupted_run:  ABANDONED
    catch_up:               false
    scheduled_job_created:  false

Two modes:

  plan     Drive the REAL CombinedBook sizing code (the production class, loaded through the
           production StrategyLoader) with a NON-SUBMITTING context, then persist an immutable
           manifest and print the review summary. Submits nothing: the context's submit_order_fn
           records OrderRequests and never imports or calls OrderRouter.

  execute  Re-verify live state against an APPROVED manifest, then submit that manifest's EXACT
           order list through POST /orders (source=STRATEGY, strategy_id=9) -> OrderRouter ->
           full risk engine. Never recomputes quantities. Aborts rather than adapting.

Run inside the backend container (it needs the app's DB, factor store, bar cache and creds):
    docker exec workbench-backend python3 /opt/workbench/ops/acct7_one_time_rebalance.py plan
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path

sys.path.insert(0, "/app")
sys.path.insert(0, "/app/data/ops/acct7")

# PROTOCOL v2 (owner rulings 2026-08-21). The continuation rule is RESOLVED here, at
# plan time, so the owner approves the rule together with the orders it governs, and
# outstanding residual debt is carried into planning so a refused exit cannot quietly
# become an intended holding when the symbol re-enters the target universe.
import v13_continuation_policy as CP  # noqa: E402
import v13_residual_debt as DEBT  # noqa: E402
os.chdir("/app")

STRATEGY_ID = 9
ACCOUNT_ID = 7
USER_ID = 7
CLASSIFICATION = {
    "execution_type": "GOVERNED_TRANSITION_TO_V13_C40",
    "construction": "Strategy 9 governance v1.3 / C40 (ADR 0049)",
    "_path_a_original": {
    "execution_type": "ONE_TIME_OPERATOR_EXECUTED_STRATEGY_REBALANCE",
    "strategy_id": STRATEGY_ID,
    "prior_interrupted_run": "ABANDONED",
    "catch_up": False,
    "scheduled_job_created": False,
}
# Container path; bind-mounted to /opt/workbench/data on the host, so manifests survive
# a container restart and are readable from the host for review.
}
MANIFEST_DIR = Path("/app/data/v13_transition")
# Limits v2 (owner ruling 2026-07-29, Option 3): feed-aware marketable-limit collar
# for single stocks after the SIP/NBBO entitlement finding. v1 stays sealed on disk.
FROZEN_LIMITS_PATH = Path(
    "/app/data/ops/acct7/ws1_evidence/v13/v13_frozen_execution_limits_v8.json")


# --------------------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------------------

def canonical(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), default=str)


def sha256_of(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def d(x) -> Decimal:
    return Decimal(str(x))


# --------------------------------------------------------------------------------------
# plan
# --------------------------------------------------------------------------------------

def cache_identity(root: Path, symbols: list[str], expected_session_date: str) -> dict:
    """Bind the BAR-CACHE identity separately from the factor-store identity.

    The two are different sources (Alpaca bars vs the Sharadar factor store) and must not be
    conflated in evidence. A rehearsal warms this cache, so a later run could silently size from
    rehearsal-era parquet unless freshness is asserted per symbol actually used.
    """
    import pandas as pd

    bucket = expected_session_date[:7]  # YYYY-MM — the open bucket
    per: dict[str, dict] = {}
    stale: list[str] = []
    for sym in symbols:
        f = root / sym.upper() / "1Day" / f"{bucket}.parquet"
        if not f.exists():
            per[sym] = {"bucket_file": str(f), "exists": False}
            stale.append(sym)
            continue
        st = f.stat()
        mtime = datetime.fromtimestamp(st.st_mtime, UTC)
        entry = {
            "bucket_file": str(f),
            "exists": True,
            "mtime_utc": mtime.isoformat(),
            "size_bytes": st.st_size,
        }
        try:
            df = pd.read_parquet(f)
            idx = df.index
            last = (
                str(max(idx)) if getattr(idx, "dtype", None) is not None
                and str(getattr(idx, "dtype", "")).startswith("datetime")
                else (str(df["t"].max()) if "t" in df.columns else None)
            )
            entry["rows"] = int(len(df))
            entry["max_bar"] = last
        except Exception as exc:  # noqa: BLE001 — record, never guess
            entry["read_error"] = str(exc)[:160]
        # Freshness: the open bucket must have been (re)written on the run's own session date.
        if mtime.date().isoformat() < expected_session_date:
            stale.append(sym)
        per[sym] = entry
    return {
        "root": str(root),
        "open_bucket": bucket,
        "expected_session_date": expected_session_date,
        "assessed_symbol_count": len(symbols),
        "symbols": per,
        "stale_or_missing_symbols": sorted(stale),
        "is_fresh": not stale,
    }


async def build_plan(reason: str, expected_session_date: str, require_fresh_cache: bool,
                     label: str, receipt_path: str | None = None) -> dict:
    from sqlalchemy import select

    from app.config import get_settings
    from app.db.models.account import Account  # noqa: F401  (registry completeness)
    from app.db.models.strategy import Strategy as StrategyRow
    from app.db.session import get_sessionmaker
    from app.factor_data.accessor import FactorAccessor
    from app.factor_data.config import resolve_store_path
    from app.factor_data.store import FactorDataStore
    from app.indicators import IndicatorComputer
    from app.market_data.bar_cache import BarCache
    from app.strategies.context import StrategyContext
    from app.strategies.loader import StrategyLoader

    settings = get_settings()
    sf = get_sessionmaker()

    # ---- pre-run live state -----------------------------------------------------------
    async with sf() as session:
        row = await session.get(StrategyRow, STRATEGY_ID)
        if row is None:
            raise SystemExit("strategy 9 not found")
        params = dict(row.params_json or {})
        symbols = list(row.symbols_json or [])
        version = row.version
        code_path = row.code_path
        status = row.status.value if hasattr(row.status, "value") else str(row.status)

        open_orders = (await session.execute(
            select(__import__("app.db.models.order", fromlist=["Order"]).Order)
        )).scalars().all()
        open_orders = [
            o for o in open_orders
            if o.account_id == ACCOUNT_ID
            and str(getattr(o.status, "value", o.status)).upper()
            not in ("FILLED", "CANCELLED", "REJECTED", "EXPIRED")
        ]

        acct_state = (await session.execute(
            __import__("sqlalchemy", fromlist=["text"]).text(
                "select equity, cash, portfolio_value, updated_at from accounts_state "
                "where account_id = :a"
            ),
            {"a": ACCOUNT_ID},
        )).first()

        pos_rows = (await session.execute(
            __import__("sqlalchemy", fromlist=["text"]).text(
                "select s.ticker, p.qty, p.market_value from positions p "
                "join symbols s on s.id = p.symbol_id where p.account_id = :a"
            ),
            {"a": ACCOUNT_ID},
        )).all()

    pre_positions = {r[0]: str(r[1]) for r in pos_rows}
    # Last mark per held name, so an EXIT (phase 1 logs no price payload) can still be
    # valued — otherwise turnover silently under-counts every exit.
    pre_marks = {
        r[0]: float(d(r[2] or 0) / d(r[1])) for r in pos_rows if d(r[1] or 0) > 0
    }
    pre_market_value = float(sum(d(r[2] or 0) for r in pos_rows))
    equity = float(acct_state[0]) if acct_state else None
    cash = float(acct_state[1]) if acct_state else None

    if open_orders:
        raise SystemExit(f"ABORT: {len(open_orders)} open order(s) on account {ACCOUNT_ID}")

    # ---- input-store identity ---------------------------------------------------------
    store_path = resolve_store_path()
    store_identity = {
        "path": str(store_path),
        "exists": store_path.exists(),
        "sha256": sha256_file(store_path) if store_path.exists() else None,
        "size_bytes": store_path.stat().st_size if store_path.exists() else None,
        "mtime_utc": (
            datetime.fromtimestamp(store_path.stat().st_mtime, UTC).isoformat()
            if store_path.exists() else None
        ),
    }
    try:
        import duckdb
        con = duckdb.connect(str(store_path), read_only=True)
        store_identity["sep_max_date"] = str(con.execute("select max(date) from sep").fetchone()[0])
        store_identity["sep_rows"] = con.execute("select count(*) from sep").fetchone()[0]
        store_identity["sep_tickers"] = con.execute(
            "select count(distinct ticker) from sep").fetchone()[0]
        con.close()
    except Exception as exc:  # noqa: BLE001 — identity is evidence; record the failure
        store_identity["coverage_error"] = str(exc)[:200]

    # ---- construct the production objects ---------------------------------------------
    # ---- OWNER RULING 2026-08-08: IDENTITY LATCH BEFORE PLANNING -----------------
    # "Require every Strategy 9 transition run to verify, before planning or dispatch:
    #  workbench account 7, strategy 9, broker account PA3BGKRLH2AP, key fingerprint
    #  5b6f39e5198d, and that the broker-returned account matches the pin."
    # Necessary here because the planner takes account state from the DB by account_id
    # and its market-data adapter (below) resolves from the environment - neither would
    # notice if the pinned identity had changed underneath it.
    import sys as _sys
    if "/app/data/ops/acct7" not in _sys.path:
        _sys.path.insert(0, "/app/data/ops/acct7")
    import v13_identity_latch as _latch
    from app.brokers.alpaca.credentials import credentials_for_mode as _cfm
    from app.db.session import get_sessionmaker as _gsm
    from app.brokers.alpaca import AlpacaAdapter as _AA
    _creds = await _cfm("paper", USER_ID, _gsm())
    _latch_adapter = _AA(_creds)
    _latch_adapter.connect()
    _latch_evidence = await _latch.verify_live(
        creds=_creds, adapter=_latch_adapter, workbench_account_id=ACCOUNT_ID,
        strategy_id=STRATEGY_ID, context="planner v3 (pre-planning)")
    _latch_adapter.disconnect()
    print("  identity latch PASS (planner): "
          + _latch_evidence["observed"]["broker_account_number"]
          + "  key fp " + _latch_evidence["observed"]["key_fingerprint"]
          + "  wb acct " + str(ACCOUNT_ID) + "  strategy " + str(STRATEGY_ID))

    from app.brokers.alpaca import AlpacaAdapter

    adapter = AlpacaAdapter()
    bar_cache = BarCache(
        adapter=adapter, root=settings.bars_cache_root, max_gb=settings.bars_cache_max_gb
    )
    factor_store = FactorDataStore(read_only=True) if store_path.exists() else None
    factor_accessor = FactorAccessor(factor_store)
    loader = StrategyLoader(Path("strategies_user"))
    cls = loader.load(code_path or "")
    merged_params = {**cls.default_params, **params}
    # `_apply_targets` sizes each name at min(equity*weight, equity*max_position_pct), so a raw
    # target weight ABOVE the cap is truncated at order time. Every projection below must use the
    # capped weight; using the raw weight overstates invested % (it read 67% vs a true 33%).
    # v1.3 (ADR 0049): NO global post-blend cap — sleeve caps act inside the
    # template's own weight construction, so book-level raw == effective.
    cap_pct = 1.0

    recorded: list[dict] = []
    signals: list[dict] = []

    async def refusing_submit(req):
        """The ONLY submit path this context has. It records and returns None; it never
        imports OrderRouter, so plan mode cannot place an order even by mistake."""
        recorded.append({
            "symbol": req.symbol_ticker,
            "side": getattr(req.side, "value", str(req.side)),
            "qty": str(req.qty),
            "type": getattr(req.type, "value", str(req.type)),
            "tif": getattr(req.tif, "value", str(req.tif)),
            "source_type": getattr(req.source_type, "value", str(req.source_type)),
            "source_id": req.source_id,
            "user_id": req.user_id,
            "account_id": req.account_id,
        })
        return None

    class PlanContext(StrategyContext):
        async def log_signal(self, symbol, type_, payload=None):
            signals.append({
                "symbol": symbol,
                "type": getattr(type_, "value", str(type_)),
                "payload": payload or {},
            })
            return 0

    ctx = PlanContext(
        strategy_id=STRATEGY_ID,
        user_id=USER_ID,
        account_id=ACCOUNT_ID,
        symbols=symbols,
        session_factory=sf,
        bar_cache=bar_cache,
        indicator_computer=IndicatorComputer(),
        submit_order_fn=refusing_submit,
        bus=None,
        factor_accessor=factor_accessor,
    )

    instance = cls(ctx=ctx, params=merged_params)
    await instance.on_init()

    # Spy on the real sizing seams so the manifest binds what production computed,
    # rather than anything this script recomputes.
    captured: dict = {}
    orig_apply = instance._apply_targets
    orig_eq = instance._equity_sleeve_weights
    orig_ca = instance._cross_asset_sleeve_weights

    async def spy_eq():
        out = await orig_eq()
        captured["equity_sleeve_weights"] = {k: float(v) for k, v in out.items()}
        return out

    async def spy_ca():
        out = await orig_ca()
        captured["cross_asset_sleeve_weights"] = {k: float(v) for k, v in out.items()}
        return out

    async def spy_apply(target, *, held, reason):
        captured["target_weights"] = {k: float(v) for k, v in target.items()}
        captured["held_at_sizing"] = {k: str(v) for k, v in held.items()}
        captured["reason"] = reason
        return await orig_apply(target, held=held, reason=reason)

    instance._equity_sleeve_weights = spy_eq
    instance._cross_asset_sleeve_weights = spy_ca
    instance._apply_targets = spy_apply

    started = datetime.now(UTC)
    await instance._rebalance()
    finished = datetime.now(UTC)

    # ---- join orders to the target_qty / price production computed --------------------
    sig_by_symbol: dict[str, dict] = {}
    for s in signals:
        p = s.get("payload") or {}
        if "target_qty" in p or "price" in p:
            sig_by_symbol[s["symbol"].upper()] = p

    orders = []
    for i, o in enumerate(recorded):
        sym = o["symbol"].upper()
        p = sig_by_symbol.get(sym, {})
        price = p.get("price")
        price_source = "sizing_payload"
        if price is None:  # phase-1 exit: no payload, value it at the last position mark
            price = pre_marks.get(sym)
            price_source = "position_mark" if price else "unavailable"
        qty = d(o["qty"])
        raw_w = captured.get("target_weights", {}).get(sym)
        orders.append({
            "seq": i + 1,
            "symbol": sym,
            "side": o["side"],
            "qty": o["qty"],
            "type": o["type"],
            "tif": o["tif"],
            "sizing_price": price,
            "price_source": price_source,
            "target_qty": p.get("target_qty"),
            "target_weight_raw": raw_w,
            "target_weight_effective": min(raw_w, cap_pct) if raw_w is not None else None,
            "intent": "exit" if raw_w is None else ("trim" if o["side"].lower() == "sell" else "entry"),
            "est_notional": float(qty * d(price)) if price else None,
        })

    sells = [o for o in orders if o["side"].lower() == "sell"]
    buys = [o for o in orders if o["side"].lower() == "buy"]

    # ---- projections -------------------------------------------------------------------
    tw = captured.get("target_weights", {})
    eq = d(equity or 0)
    cap = cap_pct
    effective = {k: min(v, cap) for k, v in tw.items()}
    raw_sum = sum(tw.values())
    eff_sum = sum(effective.values())
    projected_invested_pct = round(100.0 * eff_sum, 4) if tw else None
    projected_cash = float(eq) * (1 - eff_sum) if tw else None
    turnover = sum(o["est_notional"] or 0 for o in orders)
    unpriced = [o["symbol"] for o in orders if o["est_notional"] is None]

    truncated = sorted(
        [{"symbol": k, "raw_weight": round(v, 5), "effective_weight": cap,
          "truncated_pp": round(100.0 * (v - cap), 3)}
         for k, v in tw.items() if v > cap],
        key=lambda x: -x["raw_weight"],
    )
    at_cap = sorted(
        [{"symbol": k, "effective_weight": round(min(v, cap), 5)}
         for k, v in tw.items() if v >= cap * 0.95],
        key=lambda x: -x["effective_weight"],
    )
    largest = sorted(
        [{"symbol": k, "effective_weight": round(w, 5), "raw_weight": round(tw[k], 5),
          "notional": round(float(eq) * w, 2), "capped": tw[k] > cap}
         for k, w in effective.items()],
        key=lambda x: -x["effective_weight"],
    )[:5]

    ordered = {o["symbol"] for o in orders}
    skipped = sorted(
        s for s in tw
        if s not in ordered and d(captured.get("held_at_sizing", {}).get(s, 0)) > 0
    )

    sleeve = {
        "equity_sleeve_weight_param": merged_params.get("equity_sleeve_weight"),
        "cross_asset_weight_param": merged_params.get("cross_asset_weight"),
        "equity_sleeve_names": len(captured.get("equity_sleeve_weights", {})),
        "cross_asset_names": len(captured.get("cross_asset_sleeve_weights", {})),
        "equity_sleeve_target_sum": round(
            sum(v for k, v in tw.items()
                if k not in captured.get("cross_asset_sleeve_weights", {})), 5),
        "cross_asset_target_sum": round(
            sum(v for k, v in tw.items()
                if k in captured.get("cross_asset_sleeve_weights", {})), 5),
    }

    # ---- factor refresh receipt --------------------------------------------------------
    try:
        receipt = subprocess.run(
            ["systemctl", "show", "workbench-factor-refresh.service",
             "--property=ExecMainStatus,ExecMainExitTimestamp,Result"],
            capture_output=True, text=True, timeout=15,
        ).stdout.strip()
    except Exception as exc:  # noqa: BLE001
        receipt = f"unavailable: {exc}"

    # ---- cache identity, asserted AFTER sizing so it covers what sizing actually read ------
    assessed = sorted(
        set(captured.get("target_weights", {}))
        | {s.upper() for s in merged_params.get("cross_asset_symbols", [])}
    )
    cache = cache_identity(Path(settings.bars_cache_root), assessed, expected_session_date)
    if require_fresh_cache and not cache["is_fresh"]:
        raise SystemExit(
            "ABORT: bar cache is not fresh for the expected session date "
            f"{expected_session_date}. Stale or missing: {cache['stale_or_missing_symbols'][:20]}"
            f" ({len(cache['stale_or_missing_symbols'])} total). Rehearsal-era cached content must "
            "not become the evidence source; re-run after a live fetch, or pass "
            "--no-require-fresh-cache with a documented reason."
        )

    run_id = f"OTR-{started.strftime('%Y%m%dT%H%M%SZ')}-S9"
    body = {
        "artifact_status": label,
        "frozen_execution_limits": {
            "sha256": sha256_file(FROZEN_LIMITS_PATH),
            "content": json.loads(FROZEN_LIMITS_PATH.read_text()),
        },
        "factor_refresh_receipt_host": (
            Path(receipt_path).read_text() if receipt_path else
            "NOT EMBEDDED - rehearsal only; the governing manifest MUST embed "
            "the same-day host systemd receipt (owner requirement)"),
        "classification": CLASSIFICATION,
        "harness_sha256": sha256_file(Path(__file__).resolve()),
        "harness_path": str(Path(__file__).resolve()),
        "run_id": run_id,
        "generated_at_utc": started.isoformat(),
        "generation_seconds": round((finished - started).total_seconds(), 2),
        "strategy": {
            "id": STRATEGY_ID,
            "version": version,
            "status_at_generation": status,
            "code_path": code_path,
            "params": merged_params,
            "universe_size": len(symbols),
        },
        "inputs": {
            # Three DISTINCT identities; never conflate them in evidence.
            "authoritative_factor_store": store_identity,
            "factor_refresh_receipt": receipt,
            "bar_cache": cache,
            "source_relationship": (
                "factor store (Sharadar, /app/data/factor_data.duckdb) and bar cache (Alpaca "
                "parquet under bars_cache/) are INDEPENDENT sources. The cache is NOT derived "
                "from, and is not validated against, the factor refresh. Cache freshness is "
                "asserted separately, per symbol used, against the run's session date."
            ),
        },
        "pre_run_state": {
            "account_id": ACCOUNT_ID,
            "equity": equity,
            "cash": cash,
            "position_market_value": pre_market_value,
            "invested_pct": round(100.0 * pre_market_value / equity, 4) if equity else None,
            "position_count": len(pre_positions),
            "positions": pre_positions,
            "open_orders": len(open_orders),
        },
        "target": {
            "weights": captured.get("target_weights", {}),
            "equity_sleeve_weights": captured.get("equity_sleeve_weights", {}),
            "cross_asset_sleeve_weights": captured.get("cross_asset_sleeve_weights", {}),
            "held_at_sizing": captured.get("held_at_sizing", {}),
        },
        "orders": [
            {**o, "stage": classify_stage(
                o, {s.upper() for s in merged_params.get("cross_asset_symbols", [])})}
            for o in orders],
        "stage_totals_usd": {
            st: round(sum(abs(o.get("est_notional") or 0.0) for o in orders
                          if classify_stage(o, {s.upper() for s in
                              merged_params.get("cross_asset_symbols", [])}) == st), 2)
            for st in ("A_exits", "B_cross_asset", "C_equity")},
        "review_summary": {
            "order_count": len(orders),
            "sell_count": len(sells),
            "buy_count": len(buys),
            "estimated_turnover": round(turnover, 2),
            "orders_without_a_price": unpriced,
            "current_invested_pct": round(100.0 * pre_market_value / equity, 4) if equity else None,
            "projected_invested_pct": projected_invested_pct,
            "projected_cash": round(projected_cash, 2) if projected_cash is not None else None,
            "projected_gross_exposure": round(float(eq) * eff_sum, 2) if tw else None,
            "raw_target_weight_sum": round(raw_sum, 5),
            "effective_target_weight_sum": round(eff_sum, 5),
            "cash_from_cap_truncation_pct": round(100.0 * (raw_sum - eff_sum), 4),
            "largest_projected_positions": largest,
            "at_or_near_position_cap": at_cap,
            "truncated_by_position_cap": truncated,
            "position_cap_pct": cap,
            "held_names_skipped_by_min_trade_or_zero_delta": skipped,
            "v13_threshold": {
                "trade_floor_usd": merged_params.get("trade_floor_usd"),
                "trade_rel_pct": merged_params.get("trade_rel_pct"),
                "trade_ceiling_equity_pct": merged_params.get("trade_ceiling_equity_pct"),
            },
            "sleeve_exposure": sleeve,
        },
        "signals_emitted_during_sizing": signals,
    }

    # ---- PROTOCOL v2: resolve the continuation rule INTO the hashed body ---------------
    # The policy itself lives in the sealed limits file. Resolving it here means the
    # reviewer sees, before approving a hash, exactly which stage is completeness-required,
    # what the residual budget is, and how many failed logical orders each stage tolerates.
    # Executor v8 re-derives this from the same sealed limits and refuses any manifest
    # whose resolved block disagrees, so this is disclosure and never authority.
    body["continuation_policy_resolved"] = CP.resolve(
        body["frozen_execution_limits"]["content"], body["orders"], equity)

    # ---- PROTOCOL v2: carry outstanding residual operational debt ----------------------
    # OWNER RULING 2026-08-21: a residual "must be carried into subsequent planning and
    # must never disappear because the symbol later re-enters the target universe". The
    # planner sizes from CURRENT holdings, so without this block a name that failed to
    # exit is indistinguishable from a name we still want.
    _debt = DEBT.open_obligations(account_id=ACCOUNT_ID, strategy_id=STRATEGY_ID)
    _targets = {s.upper() for s in (captured.get("target_weights") or {})}
    body["residual_operational_debt"] = {
        "obligation": DEBT.OBLIGATION,
        "open_count": len(_debt),
        "total_open_usd": round(sum(
            float(d.get("governed_residual_valuation_usd") or 0.0) for d in _debt), 2),
        "open": _debt,
        "conflicts_with_this_target": sorted(
            {d["symbol"] for d in _debt if str(d["symbol"]).upper() in _targets}),
        "conflict_note": (
            "A symbol listed under conflicts_with_this_target failed to exit under an "
            "earlier manifest and is ALSO a target of this one. That is not an error, but "
            "it must be an explicit decision: the residual is being converted into an "
            "intended holding. Review before approving the hash."),
        "conflict_does_not_close_the_obligation": (
            "OWNER RULING 2026-08-21: re-entry into the target universe does NOT close a "
            "RESIDUAL_CLEANUP_REQUIRED obligation. It stays OPEN until closed explicitly "
            "with RESOLVED_TARGET_REENTERED_WITH_OWNER_ACCEPTANCE and a recorded owner "
            "acceptance. The planner reports the conflict; it never closes it."),
    }

    body["manifest_sha256"] = sha256_of(canonical(body))
    return body


def classify_stage(order: dict, ca_set: set) -> str:
    # DEFECT FIX 2026-07-29 (pre-governing-manifest): this planner emits the key
    # "intent" ("exit" | "trim" | "entry"); the Path A harness it was derived from
    # used "reason" ("..._exit"). The reason-only test was therefore dead code and
    # filed EVERY exit into C_equity (rehearsal OTR-20260729T003647Z: A_exits empty,
    # 37 exits in C_equity), inverting the ratified A->B->C staging and misapplying
    # the frozen limits' exits-are-exempt-from-stage-turnover rule. Accept both keys.
    if order.get("side", "").lower().startswith("sell") and (
            order.get("intent", "") == "exit"
            or order.get("reason", "").endswith("_exit")):
        return "A_exits"
    return "B_cross_asset" if order["symbol"].upper() in ca_set else "C_equity"


def print_review(m: dict) -> None:
    rs = m["review_summary"]
    pre = m["pre_run_state"]
    print("=" * 78)
    print(f"  {m['classification']['execution_type']}")
    print(f"  run_id {m['run_id']}   manifest {m['manifest_sha256'][:16]}…")
    print("=" * 78)
    print(f"  artifact_status: {m.get('artifact_status')}")
    print(f"  harness sha {m.get('harness_sha256', '?')[:16]}…")
    print(f"  strategy 9 v{m['strategy']['version']}  status {m['strategy']['status_at_generation']}")
    fs = m["inputs"]["authoritative_factor_store"]
    bc = m["inputs"]["bar_cache"]
    print(f"  factor store  sha {str(fs.get('sha256'))[:16]}…  coverage->{fs.get('sep_max_date')}")
    print(f"  bar cache     bucket {bc['open_bucket']}  fresh={bc['is_fresh']}  "
          f"assessed {bc['assessed_symbol_count']} symbols  "
          f"stale/missing {len(bc['stale_or_missing_symbols'])}")
    print(f"  equity ${pre['equity']:,.2f}   cash ${pre['cash']:,.2f}   "
          f"invested {pre['invested_pct']}%   positions {pre['position_count']}")
    print("-" * 78)
    print(f"  ORDERS {rs['order_count']}   sells {rs['sell_count']}   buys {rs['buy_count']}"
          f"   turnover ${rs['estimated_turnover']:,.2f}")
    print(f"  invested {rs['current_invested_pct']}% -> {rs['projected_invested_pct']}%   "
          f"projected cash ${rs['projected_cash']:,.2f}")
    print(f"  raw weight sum {rs['raw_target_weight_sum']} -> effective "
          f"{rs['effective_target_weight_sum']} after the {rs['position_cap_pct']*100:.1f}% cap "
          f"({rs['cash_from_cap_truncation_pct']}pp becomes cash)")
    if rs["orders_without_a_price"]:
        print(f"  ⚠ unpriced orders (excluded from turnover): {rs['orders_without_a_price']}")
    print("-" * 78)
    for label, side in (("SELLS", "sell"), ("BUYS", "buy")):
        rows = [o for o in m["orders"] if o["side"].lower() == side]
        print(f"  {label} ({len(rows)})")
        for o in rows:
            n = f"${o['est_notional']:,.2f}" if o["est_notional"] else "n/a"
            print(f"    {o['seq']:3d}  {o['symbol']:6s} {o['intent']:5s} qty {o['qty']:>14s}  "
                  f"@~{o['sizing_price']}  {n:>12s}  w={o['target_weight_effective']}")
    print("-" * 78)
    print("  5 largest projected positions (effective, post-cap):")
    for p in rs["largest_projected_positions"]:
        flag = "  <- TRUNCATED BY CAP" if p["capped"] else ""
        print(f"    {p['symbol']:6s}  {p['effective_weight']*100:.3f}%  "
              f"${p['notional']:,.2f}  (raw {p['raw_weight']*100:.3f}%){flag}")
    print(f"  at/near {rs['position_cap_pct']*100:.1f}% cap: "
          f"{[x['symbol'] for x in rs['at_or_near_position_cap']] or 'none'}")
    if rs["truncated_by_position_cap"]:
        print("  truncated by the cap:")
        for t in rs["truncated_by_position_cap"]:
            print(f"    {t['symbol']:6s} raw {t['raw_weight']*100:.3f}% -> "
                  f"{t['effective_weight']*100:.1f}%  (-{t['truncated_pp']}pp)")
    print(f"  held names skipped by min-trade/zero-delta: "
          f"{rs['held_names_skipped_by_min_trade_or_zero_delta'] or 'none'}")
    print(f"  sleeve exposure: {rs['sleeve_exposure']}")
    print("-" * 78)
    cpr = m.get("continuation_policy_resolved") or {}
    print(f"  CONTINUATION POLICY {cpr.get('policy_version')}  "
          f"counting {cpr.get('counting_unit')}  "
          f"residual budget ${cpr.get('residual_budget_usd'):,.2f}  "
          f"concentration trigger {float(cpr.get('concentration_trigger', 0)) * 100:.0f}%")
    for st, p in (cpr.get("stages") or {}).items():
        flag = ("  <- COMPLETENESS REQUIRED (joint construction; any failure halts)"
                if p["completeness_required"] else "")
        print(f"    {st:<14} {p['stage_order_count']:3d} orders  "
              f"${p['stage_notional_usd']:>12,.2f}  mode={p['mode']:<26} "
              f"tolerates {p['max_failed_orders_before_halt']} failed order(s){flag}")
        conc = ("concentration applies" if p["concentration_completeness_applies"]
                else "observability only - not a joint-construction stage")
        print(f"      largest {str(p['largest_order_symbol']):<6} "
              f"${p['largest_order_notional_usd']:>12,.2f} = "
              f"{p['largest_order_share_of_stage'] * 100:.1f}% of the stage  ({conc})")
        if p["count_rule_allowed_failed_orders"] is not None:
            print(f"      thresholds: budget ${p['effective_budget_usd']:,.2f} - backstop "
                  f"{p['backstop_failed_orders']} - count rule "
                  f"{p['count_rule_allowed_failed_orders']}  (all apply; the stricter binds)")
    debt = m.get("residual_operational_debt") or {}
    print("-" * 78)
    print(f"  RESIDUAL OPERATIONAL DEBT carried in: {debt.get('open_count', 0)} open, "
          f"${debt.get('total_open_usd', 0):,.2f}")
    for d in (debt.get("open") or []):
        print(f"    {d['symbol']:<6} {d['residual_qty']} @ "
              f"${d['governed_residual_valuation_usd']}  from {d['originating_manifest_run_id']} "
              f"({d['originating_stage']}, {d['abort_reason']})")
    if debt.get("conflicts_with_this_target"):
        print(f"    !! ALSO TARGETED BY THIS MANIFEST: {debt['conflicts_with_this_target']}")
        print("       a residual is being converted into an intended holding - decide "
              "explicitly.")
        print("       RE-ENTRY DOES NOT CLOSE THE OBLIGATION: it stays OPEN until closed "
              "with")
        print("       RESOLVED_TARGET_REENTERED_WITH_OWNER_ACCEPTANCE and a recorded owner "
              "acceptance.")
    print("=" * 78)


async def cmd_plan(args) -> None:
    session_date = args.session_date or datetime.now().astimezone().date().isoformat()
    m = await build_plan(
        reason=args.reason,
        expected_session_date=session_date,
        require_fresh_cache=not args.no_require_fresh_cache,
        label=args.label,
        receipt_path=args.receipt,
    )
    MANIFEST_DIR.mkdir(parents=True, exist_ok=True)
    prefix = "DRY_RUN_ONLY__" if "DRY_RUN" in args.label else ""
    out = MANIFEST_DIR / f"{prefix}{m['run_id']}.json"
    out.write_text(json.dumps(m, indent=1, default=str))
    out.chmod(0o444)  # immutable-by-convention once written
    print_review(m)
    print(f"\nmanifest written: {out}")
    print(f"manifest_sha256:  {m['manifest_sha256']}")
    print("\nNOTHING WAS SUBMITTED. Execution requires explicit approval of this exact manifest.")


# --------------------------------------------------------------------------------------
# execute
# --------------------------------------------------------------------------------------

async def cmd_execute(args) -> None:
    raise SystemExit(
        "EXECUTION DISABLED IN THE PLANNER: the v1.3 transition executes only via "
        "the staged executor with the frozen quote/drift gates and stage-status "
        "model (separate tool, separate owner authorization).")
    import urllib.error
    import urllib.request

    path = Path(args.manifest)
    m = json.loads(path.read_text())

    status = m.get("artifact_status", "")
    if "DRY_RUN" in status or "NOT_AUTHORIZED" in status or "SUPERSEDED" in status:
        raise SystemExit(f"ABORT: manifest is labeled {status!r} and cannot be executed.")

    stated = m.pop("manifest_sha256")
    recomputed = sha256_of(canonical(m))
    m["manifest_sha256"] = stated
    if stated != recomputed:
        raise SystemExit(f"ABORT: manifest hash mismatch\n  stated {stated}\n  actual {recomputed}")
    if args.approve_sha != stated:
        raise SystemExit(
            f"ABORT: --approve-sha does not match the manifest\n"
            f"  approved {args.approve_sha}\n  manifest {stated}"
        )
    print(f"manifest {stated[:16]}… verified, {len(m['orders'])} orders")

    # ---- safeguards: duplicate symbols / opposing orders ------------------------------
    seen: dict[str, str] = {}
    for o in m["orders"]:
        s = o["symbol"]
        if s in seen:
            raise SystemExit(f"ABORT: symbol {s} appears twice ({seen[s]} then {o['side']})")
        seen[s] = o["side"]

    # ---- re-read live state immediately before release --------------------------------
    from sqlalchemy import text

    from app.db.session import get_sessionmaker
    sf = get_sessionmaker()
    async with sf() as session:
        open_n = (await session.execute(text(
            "select count(*) from orders where account_id=:a and status not in "
            "('FILLED','CANCELLED','REJECTED','EXPIRED')"), {"a": ACCOUNT_ID})).scalar()
        pos = {r[0]: str(r[1]) for r in (await session.execute(text(
            "select s.ticker, p.qty from positions p join symbols s on s.id=p.symbol_id "
            "where p.account_id=:a"), {"a": ACCOUNT_ID})).all()}
    if open_n:
        raise SystemExit(f"ABORT: {open_n} open order(s) appeared since the manifest")

    manifest_pos = m["pre_run_state"]["positions"]
    drift = {
        s: (manifest_pos.get(s), pos.get(s))
        for s in set(manifest_pos) | set(pos)
        if str(manifest_pos.get(s)) != str(pos.get(s))
    }
    if drift and not args.accept_drift:
        print("ABORT: positions differ from the manifest:")
        for s, (was, now) in sorted(drift.items()):
            print(f"    {s}: manifest {was} -> live {now}")
        raise SystemExit("re-plan, or pass --accept-drift only with an explained cause")

    # ---- login -------------------------------------------------------------------------
    pw = os.environ.get("WB_PASSWORD")
    if not pw:
        raise SystemExit("ABORT: WB_PASSWORD not set")
    base = "http://localhost:8000/api/v1"

    def post(url, body, cookie=None):
        req = urllib.request.Request(
            url, data=json.dumps(body).encode(),
            headers={"Content-Type": "application/json", **({"Cookie": cookie} if cookie else {})},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.status, json.loads(r.read() or b"{}"), r.headers.get("set-cookie", "")

    st, _, setc = post(f"{base}/auth/login",
                       {"email": "combined-book@globalcomplyai.com", "password": pw})
    cookie = setc.split(";")[0]
    print(f"login {st}")

    short = stated[:8]
    submitted, refused = [], []
    for o in m["orders"]:
        coid = f"twb-otr-{short}-{o['seq']:03d}"
        body = {
            "symbol": o["symbol"], "side": o["side"], "qty": o["qty"],
            "type": "market", "tif": "day",
            "account_id": ACCOUNT_ID, "source": "strategy", "strategy_id": STRATEGY_ID,
            "client_order_id": coid,
        }
        if args.dry_run:
            print(f"  DRY  {o['seq']:3d} {o['side']:4s} {o['symbol']:6s} {o['qty']}  coid={coid}")
            continue
        try:
            st, resp, _ = post(f"{base}/orders", body, cookie)
            rej = resp.get("rejection_reason")
            if rej:
                refused.append((o, rej))
                print(f"  RISK REFUSAL on {o['symbol']}: {rej} — STOPPING")
                break
            submitted.append((o, resp.get("id")))
            print(f"  OK   {o['seq']:3d} {o['side']:4s} {o['symbol']:6s} {o['qty']} -> {resp.get('id')}")
        except urllib.error.HTTPError as e:
            detail = e.read().decode()[:300]
            refused.append((o, f"HTTP {e.code}: {detail}"))
            print(f"  HTTP {e.code} on {o['symbol']}: {detail} — STOPPING")
            break
        await asyncio.sleep(float(args.pacing))

    print(f"\nsubmitted {len(submitted)} / {len(m['orders'])}; refused/stopped {len(refused)}")
    log = MANIFEST_DIR / f"{m['run_id']}.execution.json"
    log.write_text(json.dumps({
        "manifest_sha256": stated,
        "classification": CLASSIFICATION,
        "operator_triggered": True,
        "submitted": [{"seq": o["seq"], "symbol": o["symbol"], "side": o["side"],
                       "qty": o["qty"], "order_id": oid} for o, oid in submitted],
        "refused": [{"seq": o["seq"], "symbol": o["symbol"], "reason": r} for o, r in refused],
        "completed_at_utc": datetime.now(UTC).isoformat(),
    }, indent=1, default=str))
    print(f"execution log: {log}")


def main() -> None:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("plan")
    p.add_argument("--reason", default="one_time_operator_rebalance")
    p.add_argument("--session-date", default=None,
                   help="YYYY-MM-DD the plan is for; defaults to today (local/ET on the box).")
    p.add_argument("--label", default="PLAN_PENDING_REVIEW",
                   help="artifact_status stamped into the manifest, e.g. DRY_RUN_ONLY.")
    p.add_argument("--receipt", default=None,
                   help="Path to the same-day HOST factor-refresh receipt to EMBED in the "
                        "hashed body (REQUIRED for the governing manifest; rehearsals may omit).")
    p.add_argument("--no-require-fresh-cache", action="store_true",
                   help="Disable the per-symbol bar-cache freshness gate (needs a documented reason).")
    p.set_defaults(fn=cmd_plan)
    e = sub.add_parser("execute")
    e.add_argument("--manifest", required=True)
    e.add_argument("--approve-sha", required=True)
    e.add_argument("--pacing", default="1.0")
    e.add_argument("--dry-run", action="store_true")
    e.add_argument("--accept-drift", action="store_true")
    e.set_defaults(fn=cmd_execute)
    args = ap.parse_args()
    asyncio.run(args.fn(args))


if __name__ == "__main__":
    main()
